---
abstract: 'OO interface into the POSIX library''s strptime'
author:
  - 'Evan Carroll <me@evancarroll.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTimeX-Format-POSIX-Strptime
no_index:
  directory:
    - inc
    - t
requires:
  DateTime::Format::CLDR: 0
  DateTimeX::Format: 0
  DateTimeX::Format::CustomPattern: 0
  Moose: 0
  POSIX::strptime: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 00.01_02
